### PR TITLE
Add support for extra environment variables

### PR DESCRIPTION
**Pull request by harshajith**
Glad to see that you have moved the helm-charts into a separate repository. Way to go!

There are certain situations we need to deploy this helm chart where it requires extra env variables. 

i.e cooperate environments normally operates behind proxy servers, hence to gain access to AWS tagging apis and other apis it requires to set proxy variables as follows as env variables inside the deployment.
`http_proxy` and `https_proxy` etc. 

I have tested this PR on AWS EKS cluster and it works fine with extra environment variables.

### CODE REVIEW

**Review by cristiangreco — APPROVED** [review]

**Comment by harshajith** [comment]
When the next release going to be for this?

**Comment by cristiangreco** [comment]
@harshajith I'll cut a new chart release soon.

**Comment by harshajith** [comment]
Quick question on this, we have many AWS accounts (1000+) to be monitored through CW exporter. In point of scaling exporters, do we have a plan or design doc how to distribute the load across multiple exporters?

**Comment by cristiangreco** [comment]
@harshajith nothing detailed planned yet around scaling. At the moment it's more about making sure that YACE features work correctly at least. I have a couple of things in mind about scaling but have postponed any work on that.

What is your current setup (where do you run YACE? how many instances? what kind of services you scrape)? What issues are you having at the moment?

**Comment by harshajith** [comment]
@cristiangreco  we deploy YACE in EKS clusters with cross account roles which has given permission to scrape CW metrics. 
I have currently added around 20 accounts into YACE config. Currently only 1 instance of YACE is running that scrape EC2, S3, RDS, ELBs and DynamoDB. 

I am wondering how to scale YACE with 800+ accounts, if I am to spin multiple YACE instance with different config files with different `rolearns` it is hard to manage within our repo.

**Comment by cristiangreco** [comment]
@harshajith do you use monitoring accounts? Are all accounts within the same region?

See https://github.com/nerdswords/yet-another-cloudwatch-exporter/issues/861

**Comment by harshajith** [comment]
@cristiangreco  We do not have a monitoring  AWS account. However, we provisioned a cross account role in all the source accounts so that we can scrape their cloud watch metrics. Now we are planning to configure YACE with all the `rolearns`. 

Another question I had was, if we increase replicas of pods, how does it work? does it duplicate the load on CW api? What is the underlying strategy of scaling?

**Comment by cristiangreco** [comment]
Given how YACE works today, you could theoretically put all available rolearns into a single config file and it will iterate over all of them (it will actually spawn a goroutine for each combination of job+rolearn+region -- the number of goroutine is currently unbound which is not ideal).

If you want to spin up multiple yace pods you would need to split the rolearns across them. The total number of requests to the cloudwatch API should be comparable to the single instance version.

How do you scrape yace / where do you store the prometheus metrics?

**Comment by harshajith** [comment]
sorry for the delay @cristiangreco and thanks for the above response!. We have currently split rolearns across multiple exporter instances. It works fine so far. 

So in this case, if we increase replica count to two in a deployment with same rolearns, it will query those AWS accounts twice from those two pods as they share the same rolears correct? 

We are storing prometheus metrics in mimir cluster and deploy exporters in EKS.

**Pull request merged**
